POST http://localhost:3000/users/user_login
Content-Type: application/json

{
  "username": "administrator",
  "password": "admin"
}

###

POST http://localhost:3000/users/user_login
Content-Type: application/json

{
  "username": "administrator",
  "password": "adminlol"
}

###

GET http://localhost:3000/users/alive
Authentication: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluaXN0cmF0b3IiLCJuYW1lIjpudWxsLCJwZXJtaXNzaW9ucyI6W3siZ3JvdXAiOiJyb290IiwidXNlcm5hbWUiOiJhZG1pbmlzdHJhdG9yIn1dLCJpYXQiOjE1ODczNjgyOTYsImV4cCI6MTU4NzM3MTg5Nn0.nWbXLA9ABgTYkhPUfM1xGg_0nvDbyGUPW948Q1LyFcqRBB1zvmItDFO5isHfaVa2wyxi2WJONiO_3-BfZr75CBj5ZjKXifa0Yi6CQ4YjD_oCRDyd-1R7lFtcn5M8SQ4H3-W7bCn46nvq4UFlMcy3Xhl8G9r478Pp70TiWpvJu_yZWQKyOvcvDAxmdBkgRDiSVgHz_vvdYtEKquV7CP0uyUKEN-aZc8GH6ZRoT8-jy6HRqe-k0RDiqcHDQqpurDay-55Ef8jJN9PeJaUOGOBGvI9xTYZHxEk4cVdEE4pz7rlbLOsODAmciVOCKP9ZmQ1zHLea1am-arcIoR8e1sbM8FwOM8XcCEcF3_tfM29fK2MYnGZOgWRFO7YsX4-4Z4ODghv6kt08t5YE-cikS0ddyPeUEnnFz9TL3zOw62F5xAm_flU-I7xgIgqS6vPxb32c15TEXXoljH0xNkCMwpIto2aySVvxcqkJbUF0pNO3VPFv0BSXONGKHSW3fxwA9KbhD7p5sAFJ16I2BSbVmKz-hPFUBd2soXcVlR00hmITXDgT1bUquQ8levAJQW8xCNZZEXTc_qMx6GXA9RY_6PiMjU3gp37jWMWpXnO0KqJspIuJqJXJ6PSWUpt5TDL5IyW3Acd6opg5onIsS-W6nvZcPPePCLpMX3VvcMMSj-L3NmE

###

PATCH http://localhost:3000/users
Authentication: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluaXN0cmF0b3IiLCJuYW1lIjoibWFyY28iLCJwZXJtaXNzaW9ucyI6W3siZ3JvdXAiOiJyb290IiwidXNlcm5hbWUiOiJhZG1pbmlzdHJhdG9yIn1dLCJpYXQiOjE1ODczNzE5NTcsImV4cCI6MTU4NzM3NTU1N30.dPPurVs3BNXwjyofgazb6gmQwn8ckYd5WSNHhKjkf7zIHrgXB7ccYn_hW5gmQoq_NeUprwOw9BabiSvd2C1d_5xveaaTcXBoDOnMgFVnkifa_vKE1-WIOG8B2dY1F2YCNIO148VZuhREdXUEWVqpxX3DkddRFMk2pbBRZ5TxuNDvgVgNTlgkZNuXNddUxgoi4jnBF6VJz46wgZnTf6Kf13-cRoMdm_kn6hVRC0AJst627S4ZNCwV1cn0b6ZVVvicqH8tAX9LfvqWmzEfSA_VLoq72ETNAQPnFu7pU4RqTlAEDixYBwEJiIu0324aHFR2oNvNKN8EUqOAZvmRbpQG6P-DX8SExGGAo3ky63irUF_zDjpsd7IkWr-G72zN61lNB1ubcoxEB_q2isMyfIs9tcjRvnVolpTznMA5Jf4CxfPPDAF-XsDAq-z6q4o-mn1kpFzTjjpOL60i5R2m5MK_QnDQQrn_ZF-eDGpTVdYLfW4u_Teu1fQ6iprofyHr38ZIczENafCBz0Zc-cSSCDuL7a_64G5Zh3Yzli7X4SigeGLePyEonQcrxB_eX0k8W44VeIbPwXLU6SOA1ssZDHkeTV5XfqJZo-bYuHJGFLagw2vBSD3jI_6abx1OC4TRgb6UACiOq-iTZUtcV4MqbAlZkSrI2g_faTYQaVr224e6DFQ
Content-Type: application/json

{
  "username": "administrator",
  "newpassword": "giorgio",
  "oldpassword": "admin",
  "permissions": ["root", "bagno"],
  "name": "marco"
}
###