POST http://localhost:3000/users/user_login
Content-Type: application/json

{
  "username": "administrator",
  "password": "admin"
}

###

POST http://localhost:3000/users/user_login
Content-Type: application/json

{
  "username": "administrator",
  "password": "adminlol"
}

###

GET http://localhost:3000/users/alive
Authentication: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluaXN0cmF0b3IiLCJuYW1lIjpudWxsLCJwZXJtaXNzaW9ucyI6W3siZ3JvdXAiOiJyb290IiwidXNlcm5hbWUiOiJhZG1pbmlzdHJhdG9yIn1dLCJpYXQiOjE1ODY4NjI0NDksImV4cCI6MTU4Njg2NjA0OX0.c2iiB6sGRMNwHZ0hKDY3tVxJaznLsvKGDXKxKMDGXahYkJE_NiUoVy9oUOdOpUyx_JwfwlYD8Ne3odK06o_LP0x6aX_IntKRyWp0AQs5wqnrZ_bhBgjsbJTGmIvv4MIGsJ0G9Na4HF4bFfKeP-4QiCBuqFSFF9hlqBo1SlYZR1f6CMNQUVOAK6MzkJZjTn-10ZosKw6B3ZcgOzVXFpD394VwBm05OEPPe7ipucjJzrJMUh6MRXi0Oc6kqXMzc3UU8JibzxAqxPaMX_aB5S6mVY0m7oP5ax2hS9j36yxOHG9TBkVbARUvyNKP1DSwFOrkPiaUQN9dgsVPmvAxAX9RI6XsEVF1cewrdyESEUCjNEsk8ed6i1GGRoO3XbaDGgO_DCza-ulXFdBDC3i0X7_pbtAIXAIb0CDg387qMELfEvOSQn-gi-esfDZ1Q2YW-BGYsA9K0Kq7cDg1zg1-7BK9iFqYLDG3897s3xvA0LpTNm6CNnyW_DOklK5SGQyzwRdthpqbHBzvg9jG_LAx0TeQArivmaf_aW8qecscIUA99yPFnmuBJp0yQ3uMmssUiN2GKXwjLf64Ml0wsgVIb-e5i5K1m_GuFykj_fYRarA5DkyPXNdIqk8NiPS46rMf2_2C2a2gLxqEJf43MOXobL1yzF287q1_wuDvpMF6E0jSbmQ

###

//eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluaXN0cmF0b3IiLCJuYW1lIjpudWxsLCJwZXJtaXNzaW9ucyI6W3siZ3JvdXAiOiJyb290IiwidXNlcm5hbWUiOiJhZG1pbmlzdHJhdG9yIn1dLCJpYXQiOjE1ODY4NjI0NDksImV4cCI6MTU4Njg2NjA0OX0.c2iiB6sGRMNwHZ0hKDY3tVxJaznLsvKGDXKxKMDGXahYkJE_NiUoVy9oUOdOpUyx_JwfwlYD8Ne3odK06o_LP0x6aX_IntKRyWp0AQs5wqnrZ_bhBgjsbJTGmIvv4MIGsJ0G9Na4HF4bFfKeP-4QiCBuqFSFF9hlqBo1SlYZR1f6CMNQUVOAK6MzkJZjTn-10ZosKw6B3ZcgOzVXFpD394VwBm05OEPPe7ipucjJzrJMUh6MRXi0Oc6kqXMzc3UU8JibzxAqxPaMX_aB5S6mVY0m7oP5ax2hS9j36yxOHG9TBkVbARUvyNKP1DSwFOrkPiaUQN9dgsVPmvAxAX9RI6XsEVF1cewrdyESEUCjNEsk8ed6i1GGRoO3XbaDGgO_DCza-ulXFdBDC3i0X7_pbtAIXAIb0CDg387qMELfEvOSQn-gi-esfDZ1Q2YW-BGYsA9K0Kq7cDg1zg1-7BK9iFqYLDG3897s3xvA0LpTNm6CNnyW_DOklK5SGQyzwRdthpqbHBzvg9jG_LAx0TeQArivmaf_aW8qecscIUA99yPFnmuBJp0yQ3uMmssUiN2GKXwjLf64Ml0wsgVIb-e5i5K1m_GuFykj_fYRarA5DkyPXNdIqk8NiPS46rMf2_2C2a2gLxqEJf43MOXobL1yzF287q1_wuDvpMF6E0jSbmQ